name: MasterRankingScope
package: masterRankingScope
comment: "ランキング範囲"

structure:
  Id:
    name: id
    type: int64
    nullable: false
    number: 1
    comment: "ID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "ランキング範囲名"
  RankingScopeType:
    name: ranking_scope_type
    type: enum
    nullable: false
    number: 3
    comment: "ランキング範囲タイプ"
primary:
  - Id
unique:
  - Id
index:
  - RankingScopeType
