// Code generated by MockGen. DO NOT EDIT.
// Source: ./common_shard_mysql_repository.gen.go

// Package commonShard is a generated GoMock package.
package commonShard

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockCommonShardMysqlRepository is a mock of CommonShardMysqlRepository interface.
type MockCommonShardMysqlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommonShardMysqlRepositoryMockRecorder
}

// MockCommonShardMysqlRepositoryMockRecorder is the mock recorder for MockCommonShardMysqlRepository.
type MockCommonShardMysqlRepositoryMockRecorder struct {
	mock *MockCommonShardMysqlRepository
}

// NewMockCommonShardMysqlRepository creates a new mock instance.
func NewMockCommonShardMysqlRepository(ctrl *gomock.Controller) *MockCommonShardMysqlRepository {
	mock := &MockCommonShardMysqlRepository{ctrl: ctrl}
	mock.recorder = &MockCommonShardMysqlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonShardMysqlRepository) EXPECT() *MockCommonShardMysqlRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockCommonShardMysqlRepository) Create(ctx context.Context, tx *gorm.DB, m *CommonShard) (*CommonShard, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, tx, m)
	ret0, _ := ret[0].(*CommonShard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) Create(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).Create), ctx, tx, m)
}

// CreateList mocks base method.
func (m *MockCommonShardMysqlRepository) CreateList(ctx context.Context, tx *gorm.DB, ms CommonShards) (CommonShards, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateList", ctx, tx, ms)
	ret0, _ := ret[0].(CommonShards)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateList indicates an expected call of CreateList.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) CreateList(ctx, tx, ms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateList", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).CreateList), ctx, tx, ms)
}

// Delete mocks base method.
func (m_2 *MockCommonShardMysqlRepository) Delete(ctx context.Context, tx *gorm.DB, m *CommonShard) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Delete", ctx, tx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) Delete(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).Delete), ctx, tx, m)
}

// Find mocks base method.
func (m *MockCommonShardMysqlRepository) Find(ctx context.Context, id int64) (*CommonShard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*CommonShard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).Find), ctx, id)
}

// FindByShardKey mocks base method.
func (m *MockCommonShardMysqlRepository) FindByShardKey(ctx context.Context, shardKey string) (*CommonShard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShardKey", ctx, shardKey)
	ret0, _ := ret[0].(*CommonShard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShardKey indicates an expected call of FindByShardKey.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) FindByShardKey(ctx, shardKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShardKey", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).FindByShardKey), ctx, shardKey)
}

// FindList mocks base method.
func (m *MockCommonShardMysqlRepository) FindList(ctx context.Context) (CommonShards, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx)
	ret0, _ := ret[0].(CommonShards)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) FindList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).FindList), ctx)
}

// FindListByShardKey mocks base method.
func (m *MockCommonShardMysqlRepository) FindListByShardKey(ctx context.Context, shardKey string) (CommonShards, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindListByShardKey", ctx, shardKey)
	ret0, _ := ret[0].(CommonShards)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindListByShardKey indicates an expected call of FindListByShardKey.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) FindListByShardKey(ctx, shardKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindListByShardKey", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).FindListByShardKey), ctx, shardKey)
}

// FindOrNil mocks base method.
func (m *MockCommonShardMysqlRepository) FindOrNil(ctx context.Context, id int64) (*CommonShard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNil", ctx, id)
	ret0, _ := ret[0].(*CommonShard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNil indicates an expected call of FindOrNil.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) FindOrNil(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNil", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).FindOrNil), ctx, id)
}

// FindOrNilByShardKey mocks base method.
func (m *MockCommonShardMysqlRepository) FindOrNilByShardKey(ctx context.Context, shardKey string) (*CommonShard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNilByShardKey", ctx, shardKey)
	ret0, _ := ret[0].(*CommonShard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNilByShardKey indicates an expected call of FindOrNilByShardKey.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) FindOrNilByShardKey(ctx, shardKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNilByShardKey", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).FindOrNilByShardKey), ctx, shardKey)
}

// Update mocks base method.
func (m_2 *MockCommonShardMysqlRepository) Update(ctx context.Context, tx *gorm.DB, m *CommonShard) (*CommonShard, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, tx, m)
	ret0, _ := ret[0].(*CommonShard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommonShardMysqlRepositoryMockRecorder) Update(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommonShardMysqlRepository)(nil).Update), ctx, tx, m)
}
