
CREATE TABLE shard (

	id BIGINT NOT NULL AUTO_INCREMENT,

	name VARCHAR(255) NOT NULL,

	count INT NOT NULL,

	created_at TIMESTAMP NOT NULL,

	updated_at TIMESTAMP NOT NULL,

	PRIMARY KEY(id),
	
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
