version: '3.8'

name: echo-ddd-test

services:
# Test DB
  test_db:
    container_name: echo-ddd-db-test
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: echo_ddd_test
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/test_db/data:/var/lib/mysql  
      - ./docker/test_db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/test_db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# API Test
  test_api:
    container_name: echo-ddd-api-test
    environment:
      MYSQL_DATABASE: echo_ddd_test
      MYSQL_WRITE_USER: mysql_user
      MYSQL_WRITE_PASSWORD: mysql_password
      MYSQL_WRITE_HOST: echo-ddd-db-test
      MYSQL_READ_USER: mysql_user
      MYSQL_READ_PASSWORD: mysql_password
      MYSQL_READ_HOST: echo-ddd-db-test
      TEST_API_URL: http://0.0.0.0:8000
      AUTH_SECRET: secret_key
    build:
      target: dev
      context: .
      dockerfile: ./docker/test_api/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      test_db:
        condition: service_healthy
