version: '3.8'

name: gocrafter

services:
  # DB
  db:
    container_name: gocrafter-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: echo_ddd_api_local
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql  
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Gen
  gen:
    container_name: gocrafter-gen
    env_file:
      - .env.api.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/gen/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

  # API
  api:
    container_name: gocrafter-api
    env_file:
      - .env.api.local
    build: 
      target: dev
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      db:
        condition: service_healthy

  # Batch
  batch:
    container_name: gocrafter-batch
    env_file:
      - .env.api.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/batch/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

  # Swagger
  swagger:
    container_name: gocrafter-swagger
    env_file:
      - .env.api.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/swagger/Dockerfile
    volumes:
      - .:/swagger:cached
    ports:
      - "8000:8000"
    tty: true
