version: '3.8'

name: gocrafter-test

services:
  # UserDB
  test_db_user:
    container_name: gocrafter-test-db-user
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: gocrafter_user_test
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/test_db_user/data:/var/lib/mysql  
      - ./docker/test_db_user/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/test_db_user/sql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  # MasterDB
  test_db_master:
    container_name: gocrafter-test-db-master
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: gocrafter_master_test
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/test_db_master/data:/var/lib/mysql  
      - ./docker/test_db_master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/test_db_master/sql:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# API Test
  test_api:
    container_name: gocrafter-test-api
    env_file:
      - .env.test
    build:
      target: dev
      context: .
      dockerfile: ./docker/test_api/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      test_db_user:
        condition: service_healthy
      test_db_master:
        condition: service_healthy
