version: '3.8'

name: echo-ddd-local

services:
  # DB
  db_api:
    container_name: echo-ddd-db-api
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: echo_ddd_api_local
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db_api/data:/var/lib/mysql  
      - ./docker/db_api/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db_api/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Gen
  gen:
    container_name: echo-ddd-gen
    env_file:
      - .env.api.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/gen/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      db_api:
        condition: service_healthy

  # API
  api:
    container_name: echo-ddd-api
    env_file:
      - .env.api.local
    build: 
      target: dev
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      db_api:
        condition: service_healthy

  # Batch
  batch:
    container_name: echo-ddd-batch
    env_file:
      - .env.api.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/batch/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      db_api:
        condition: service_healthy

  # Swagger
  swagger:
    container_name: echo-ddd-swagger
    env_file:
      - .env.api.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/swagger/Dockerfile
    volumes:
      - .:/swagger:cached
    ports:
      - "8000:8000"
    tty: true
