version: '3.8'

name: gocrafter-server

volumes:
  mysql-local:
    driver: local
  redis-local:
    driver: local

services:
  mysql:
    container_name: gocrafter-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-local:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    container_name: gocrafter-redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/etc/redis.conf
      - redis-local:/data
    tty: true

  generator:
    container_name: gocrafter-generator
    env_file:
      - .env.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/generator/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - mysql
      - redis

  api-game:
    container_name: gocrafter-api-game
    env_file:
      - .env.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/api/game/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - mysql
      - redis

  multi-game:
    container_name: gocrafter-api-multi
    env_file:
      - .env.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/api/multi/Dockerfile
    ports:
      - "50052:50051"
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - mysql
      - redis
