version: '3.8'

name: gocrafter

services:
  db:
    container_name: gocrafter-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-local:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  gen:
    container_name: gocrafter-gen
    env_file:
      - .env.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/gen/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: gocrafter-api
    env_file:
      - .env.local
    build: 
      target: dev
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      db:
        condition: service_healthy

  auth:
    container_name: gocrafter-auth
    env_file:
      - .env.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - "8002:8000"
    tty: true
    depends_on:
      db:
        condition: service_healthy

  batch:
    container_name: gocrafter-batch
    env_file:
      - .env.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/batch/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

  swagger:
    container_name: gocrafter-swagger
    env_file:
      - .env.local
    build:
      target: dev
      context: .
      dockerfile: ./docker/swagger/Dockerfile
    volumes:
      - .:/swagger:cached
    ports:
      - "8000:8000"
    tty: true

volumes:
  db-local:
    driver: local
