version: '3.8'

name: gocrafter-test

services:
  test_db:
    container_name: gocrafter-test-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/test_db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/test_db/init:/docker-entrypoint-initdb.d
      - db-local-test:/var/lib/mysql
    ports:
      - "3307:3306"
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  test_api:
    container_name: gocrafter-test-api
    env_file:
      - .env.test
    build:
      target: dev
      context: .
      dockerfile: ./docker/test_api/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      test_db:
        condition: service_healthy

volumes:
   db-local-test:
     driver: local
