
CREATE TABLE example (

	id BIGINT NOT NULL AUTO_INCREMENT,

	name VARCHAR(255) NOT NULL,

	detail VARCHAR(255) DEFAULT NULL,

	count INT NOT NULL,

	created_at TIMESTAMP NOT NULL,

	updated_at TIMESTAMP NOT NULL,

	PRIMARY KEY(id),
	INDEX(name)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
