
CREATE TABLE event (

	id BIGINT NOT NULL AUTO_INCREMENT,

	name VARCHAR(255) NOT NULL,

	reset_hour INT DEFAULT NULL,

	repeat_setting TINYINT NOT NULL,

	repeat_start_at TIMESTAMP DEFAULT NULL,

	start_at TIMESTAMP DEFAULT NULL,

	end_at TIMESTAMP DEFAULT NULL,

	created_at TIMESTAMP NOT NULL,

	updated_at TIMESTAMP NOT NULL,

	PRIMARY KEY(id),
	INDEX(name)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
