// Code generated by MockGen. DO NOT EDIT.
// Source: ./user_account_repository.gen.go

// Package userAccount is a generated GoMock package.
package userAccount

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserAccountRepository is a mock of UserAccountRepository interface.
type MockUserAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserAccountRepositoryMockRecorder
}

// MockUserAccountRepositoryMockRecorder is the mock recorder for MockUserAccountRepository.
type MockUserAccountRepositoryMockRecorder struct {
	mock *MockUserAccountRepository
}

// NewMockUserAccountRepository creates a new mock instance.
func NewMockUserAccountRepository(ctrl *gomock.Controller) *MockUserAccountRepository {
	mock := &MockUserAccountRepository{ctrl: ctrl}
	mock.recorder = &MockUserAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAccountRepository) EXPECT() *MockUserAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockUserAccountRepository) Create(ctx context.Context, tx *gorm.DB, m *UserAccount) (*UserAccount, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, tx, m)
	ret0, _ := ret[0].(*UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserAccountRepositoryMockRecorder) Create(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserAccountRepository)(nil).Create), ctx, tx, m)
}

// CreateList mocks base method.
func (m *MockUserAccountRepository) CreateList(ctx context.Context, tx *gorm.DB, ms UserAccounts) (UserAccounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateList", ctx, tx, ms)
	ret0, _ := ret[0].(UserAccounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateList indicates an expected call of CreateList.
func (mr *MockUserAccountRepositoryMockRecorder) CreateList(ctx, tx, ms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateList", reflect.TypeOf((*MockUserAccountRepository)(nil).CreateList), ctx, tx, ms)
}

// Delete mocks base method.
func (m_2 *MockUserAccountRepository) Delete(ctx context.Context, tx *gorm.DB, m *UserAccount) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Delete", ctx, tx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserAccountRepositoryMockRecorder) Delete(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserAccountRepository)(nil).Delete), ctx, tx, m)
}

// Find mocks base method.
func (m *MockUserAccountRepository) Find(ctx context.Context, userId string) (*UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userId)
	ret0, _ := ret[0].(*UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserAccountRepositoryMockRecorder) Find(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserAccountRepository)(nil).Find), ctx, userId)
}

// FindList mocks base method.
func (m *MockUserAccountRepository) FindList(ctx context.Context, userId string) (UserAccounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx, userId)
	ret0, _ := ret[0].(UserAccounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockUserAccountRepositoryMockRecorder) FindList(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockUserAccountRepository)(nil).FindList), ctx, userId)
}

// FindOrNil mocks base method.
func (m *MockUserAccountRepository) FindOrNil(ctx context.Context, userId string) (*UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNil", ctx, userId)
	ret0, _ := ret[0].(*UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNil indicates an expected call of FindOrNil.
func (mr *MockUserAccountRepositoryMockRecorder) FindOrNil(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNil", reflect.TypeOf((*MockUserAccountRepository)(nil).FindOrNil), ctx, userId)
}

// Update mocks base method.
func (m_2 *MockUserAccountRepository) Update(ctx context.Context, tx *gorm.DB, m *UserAccount) (*UserAccount, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, tx, m)
	ret0, _ := ret[0].(*UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserAccountRepositoryMockRecorder) Update(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserAccountRepository)(nil).Update), ctx, tx, m)
}
