name: CommonRankingWorld
package: commonRankingWorld
comment: "ワールドランキング"

structure:
  MasterRankingId:
    name: master_ranking_id
    type: int64
    nullable: false
    number: 1
    comment: "マスターランキングID"
  UserId:
    name: user_id
    type: string
    nullable: false
    number: 2
    comment: "ユーザーID"
  Score:
    name: score
    type: int32
    nullable: false
    number: 3
    comment: "スコア"
  RankedAt:
    name: ranked_at
    type: time
    nullable: false
    number: 5
    comment: "ランク付け日時"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 6
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 7
    comment: "更新日時"
primary:
  - MasterRankingId,UserId
unique:
  - MasterRankingId,UserId
index:
  - MasterRankingId
