// Code generated by MockGen. DO NOT EDIT.
// Source: ./common_transaction_mysql_repository.gen.go

// Package commonTransaction is a generated GoMock package.
package commonTransaction

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockCommonTransactionMysqlRepository is a mock of CommonTransactionMysqlRepository interface.
type MockCommonTransactionMysqlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommonTransactionMysqlRepositoryMockRecorder
}

// MockCommonTransactionMysqlRepositoryMockRecorder is the mock recorder for MockCommonTransactionMysqlRepository.
type MockCommonTransactionMysqlRepositoryMockRecorder struct {
	mock *MockCommonTransactionMysqlRepository
}

// NewMockCommonTransactionMysqlRepository creates a new mock instance.
func NewMockCommonTransactionMysqlRepository(ctrl *gomock.Controller) *MockCommonTransactionMysqlRepository {
	mock := &MockCommonTransactionMysqlRepository{ctrl: ctrl}
	mock.recorder = &MockCommonTransactionMysqlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonTransactionMysqlRepository) EXPECT() *MockCommonTransactionMysqlRepositoryMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockCommonTransactionMysqlRepository) Begin(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockCommonTransactionMysqlRepositoryMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockCommonTransactionMysqlRepository)(nil).Begin), ctx)
}

// Commit mocks base method.
func (m *MockCommonTransactionMysqlRepository) Commit(ctx context.Context, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockCommonTransactionMysqlRepositoryMockRecorder) Commit(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockCommonTransactionMysqlRepository)(nil).Commit), ctx, tx)
}

// Rollback mocks base method.
func (m *MockCommonTransactionMysqlRepository) Rollback(ctx context.Context, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockCommonTransactionMysqlRepositoryMockRecorder) Rollback(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockCommonTransactionMysqlRepository)(nil).Rollback), ctx, tx)
}
