name: MasterAction
package: masterAction
comment: "アクション"

structure:
  Id:
    name: id
    type: int64
    nullable: false
    number: 1
    comment: "ID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "アクション名"
  ActionStepType:
    name: action_step_type
    type: enum
    nullable: false
    number: 3
    comment: "アクションステップタイプ"
  ActionTriggerType:
    name: action_trigger_type
    type: enum
    nullable: false
    number: 4
    comment: "アクショントリガータイプ"
  AnyId:
    name: any_id
    type: int64
    nullable: true
    number: 5
    comment: "対象のID"
  TriggerActionId:
    name: trigger_action_id
    type: int64
    nullable: true
    number: 6
    comment: "トリガーになるアクションのID"
  Expiration:
    name: expiration
    type: int32
    nullable: true
    number: 7
    comment: "有効期限"
primary:
  - Id
unique:
  - Id
index:
  - Name
  - ActionStepType
  - AnyId
  - ActionStepType,AnyId
