// 放置ボーナスイベント

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: master_idle_bonus_event_structure.proto

package idleBonus

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MasterIdleBonusEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResetHour     int32                  `protobuf:"varint,3,opt,name=reset_hour,json=resetHour,proto3" json:"reset_hour,omitempty"`
	IntervalHour  int32                  `protobuf:"varint,4,opt,name=interval_hour,json=intervalHour,proto3" json:"interval_hour,omitempty"`
	RepeatSetting bool                   `protobuf:"varint,5,opt,name=repeat_setting,json=repeatSetting,proto3" json:"repeat_setting,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_at,json=endAt,proto3,oneof" json:"end_at,omitempty"`
}

func (x *MasterIdleBonusEvent) Reset() {
	*x = MasterIdleBonusEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_master_idle_bonus_event_structure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterIdleBonusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterIdleBonusEvent) ProtoMessage() {}

func (x *MasterIdleBonusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_master_idle_bonus_event_structure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterIdleBonusEvent.ProtoReflect.Descriptor instead.
func (*MasterIdleBonusEvent) Descriptor() ([]byte, []int) {
	return file_master_idle_bonus_event_structure_proto_rawDescGZIP(), []int{0}
}

func (x *MasterIdleBonusEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MasterIdleBonusEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MasterIdleBonusEvent) GetResetHour() int32 {
	if x != nil {
		return x.ResetHour
	}
	return 0
}

func (x *MasterIdleBonusEvent) GetIntervalHour() int32 {
	if x != nil {
		return x.IntervalHour
	}
	return 0
}

func (x *MasterIdleBonusEvent) GetRepeatSetting() bool {
	if x != nil {
		return x.RepeatSetting
	}
	return false
}

func (x *MasterIdleBonusEvent) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *MasterIdleBonusEvent) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

var File_master_idle_bonus_event_structure_proto protoreflect.FileDescriptor

var file_master_idle_bonus_event_structure_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x6c, 0x65, 0x5f, 0x62, 0x6f,
	0x6e, 0x75, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x14, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x6c, 0x65,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x73, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x48, 0x6f,
	0x75, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74,
	0x12, 0x36, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x6e, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x65, 0x6e, 0x64,
	0x5f, 0x61, 0x74, 0x42, 0x28, 0x5a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x69, 0x64, 0x6c, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_master_idle_bonus_event_structure_proto_rawDescOnce sync.Once
	file_master_idle_bonus_event_structure_proto_rawDescData = file_master_idle_bonus_event_structure_proto_rawDesc
)

func file_master_idle_bonus_event_structure_proto_rawDescGZIP() []byte {
	file_master_idle_bonus_event_structure_proto_rawDescOnce.Do(func() {
		file_master_idle_bonus_event_structure_proto_rawDescData = protoimpl.X.CompressGZIP(file_master_idle_bonus_event_structure_proto_rawDescData)
	})
	return file_master_idle_bonus_event_structure_proto_rawDescData
}

var file_master_idle_bonus_event_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_master_idle_bonus_event_structure_proto_goTypes = []interface{}{
	(*MasterIdleBonusEvent)(nil),  // 0: proto.MasterIdleBonusEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_master_idle_bonus_event_structure_proto_depIdxs = []int32{
	1, // 0: proto.MasterIdleBonusEvent.start_at:type_name -> google.protobuf.Timestamp
	1, // 1: proto.MasterIdleBonusEvent.end_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_master_idle_bonus_event_structure_proto_init() }
func file_master_idle_bonus_event_structure_proto_init() {
	if File_master_idle_bonus_event_structure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_master_idle_bonus_event_structure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterIdleBonusEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_master_idle_bonus_event_structure_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_master_idle_bonus_event_structure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_master_idle_bonus_event_structure_proto_goTypes,
		DependencyIndexes: file_master_idle_bonus_event_structure_proto_depIdxs,
		MessageInfos:      file_master_idle_bonus_event_structure_proto_msgTypes,
	}.Build()
	File_master_idle_bonus_event_structure_proto = out.File
	file_master_idle_bonus_event_structure_proto_rawDesc = nil
	file_master_idle_bonus_event_structure_proto_goTypes = nil
	file_master_idle_bonus_event_structure_proto_depIdxs = nil
}
