name: MasterConfig
package: masterConfig
comment: "設定"

structure:
  Id:
    name: id
    type: int64
    nullable: false
    number: 1
    comment: "ID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "設定名"
  ConfigType:
    name: config_type
    type: enum
    nullable: false
    number: 3
    comment: "設定タイプ"
  Value:
    name: value
    type: string
    nullable: false
    number: 4
    comment: "設定値"
primary:
  - Id
unique:
  - Id
index:
  - ConfigType
