name: MasterActionStep
package: masterActionStep
comment: "アクションステップ"

structure:
  Id:
    name: id
    type: int64
    nullable: false
    number: 1
    comment: "ID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "アクションステップ名"
  ActionStepType:
    name: action_step_type
    type: enum
    nullable: false
    number: 3
    comment: "アクションステップタイプ"
primary:
  - Id
unique:
  - Id
index:
  - ActionStepType
