name: CommonRoom
package: commonRoom
comment: "ルーム"

structure:
  RoomId:
    name: room_id
    type: string
    nullable: false
    number: 1
    comment: "ルームID"
  HostUserId:
    name: host_user_id
    type: string
    nullable: false
    number: 2
    comment: "作成したユーザーID"
  RoomNumber:
    name: room_number
    type: int32
    nullable: false
    number: 3
    comment: "ルーム番号"
  Name:
    name: name
    type: string
    nullable: false
    number: 4
    comment: "ルーム名"
  UserCount:
    name: user_count
    type: int32
    nullable: false
    number: 5
    comment: "ユーザー数"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 6
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 7
    comment: "更新日時"
primary:
  - RoomId
unique:
  - RoomId
index:
  - HostUserId
