// Code generated by MockGen. DO NOT EDIT.
// Source: ./master_ranking_scope_mysql_repository.gen.go

// Package masterRankingScope is a generated GoMock package.
package masterRankingScope

import (
	context "context"
	reflect "reflect"

	enum "github.com/game-core/gocrafter/pkg/domain/enum"
	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockMasterRankingScopeMysqlRepository is a mock of MasterRankingScopeMysqlRepository interface.
type MockMasterRankingScopeMysqlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMasterRankingScopeMysqlRepositoryMockRecorder
}

// MockMasterRankingScopeMysqlRepositoryMockRecorder is the mock recorder for MockMasterRankingScopeMysqlRepository.
type MockMasterRankingScopeMysqlRepositoryMockRecorder struct {
	mock *MockMasterRankingScopeMysqlRepository
}

// NewMockMasterRankingScopeMysqlRepository creates a new mock instance.
func NewMockMasterRankingScopeMysqlRepository(ctrl *gomock.Controller) *MockMasterRankingScopeMysqlRepository {
	mock := &MockMasterRankingScopeMysqlRepository{ctrl: ctrl}
	mock.recorder = &MockMasterRankingScopeMysqlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterRankingScopeMysqlRepository) EXPECT() *MockMasterRankingScopeMysqlRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockMasterRankingScopeMysqlRepository) Create(ctx context.Context, tx *gorm.DB, m *MasterRankingScope) (*MasterRankingScope, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, tx, m)
	ret0, _ := ret[0].(*MasterRankingScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) Create(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).Create), ctx, tx, m)
}

// CreateList mocks base method.
func (m *MockMasterRankingScopeMysqlRepository) CreateList(ctx context.Context, tx *gorm.DB, ms MasterRankingScopes) (MasterRankingScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateList", ctx, tx, ms)
	ret0, _ := ret[0].(MasterRankingScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateList indicates an expected call of CreateList.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) CreateList(ctx, tx, ms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateList", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).CreateList), ctx, tx, ms)
}

// Delete mocks base method.
func (m_2 *MockMasterRankingScopeMysqlRepository) Delete(ctx context.Context, tx *gorm.DB, m *MasterRankingScope) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Delete", ctx, tx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) Delete(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).Delete), ctx, tx, m)
}

// Find mocks base method.
func (m *MockMasterRankingScopeMysqlRepository) Find(ctx context.Context, id int64) (*MasterRankingScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*MasterRankingScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).Find), ctx, id)
}

// FindByRankingType mocks base method.
func (m *MockMasterRankingScopeMysqlRepository) FindByRankingType(ctx context.Context, rankingType enum.RankingType) (*MasterRankingScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRankingType", ctx, rankingType)
	ret0, _ := ret[0].(*MasterRankingScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRankingType indicates an expected call of FindByRankingType.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) FindByRankingType(ctx, rankingType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRankingType", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).FindByRankingType), ctx, rankingType)
}

// FindList mocks base method.
func (m *MockMasterRankingScopeMysqlRepository) FindList(ctx context.Context) (MasterRankingScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx)
	ret0, _ := ret[0].(MasterRankingScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) FindList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).FindList), ctx)
}

// FindListByRankingType mocks base method.
func (m *MockMasterRankingScopeMysqlRepository) FindListByRankingType(ctx context.Context, rankingType enum.RankingType) (MasterRankingScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindListByRankingType", ctx, rankingType)
	ret0, _ := ret[0].(MasterRankingScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindListByRankingType indicates an expected call of FindListByRankingType.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) FindListByRankingType(ctx, rankingType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindListByRankingType", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).FindListByRankingType), ctx, rankingType)
}

// FindOrNil mocks base method.
func (m *MockMasterRankingScopeMysqlRepository) FindOrNil(ctx context.Context, id int64) (*MasterRankingScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNil", ctx, id)
	ret0, _ := ret[0].(*MasterRankingScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNil indicates an expected call of FindOrNil.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) FindOrNil(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNil", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).FindOrNil), ctx, id)
}

// FindOrNilByRankingType mocks base method.
func (m *MockMasterRankingScopeMysqlRepository) FindOrNilByRankingType(ctx context.Context, rankingType enum.RankingType) (*MasterRankingScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNilByRankingType", ctx, rankingType)
	ret0, _ := ret[0].(*MasterRankingScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNilByRankingType indicates an expected call of FindOrNilByRankingType.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) FindOrNilByRankingType(ctx, rankingType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNilByRankingType", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).FindOrNilByRankingType), ctx, rankingType)
}

// Update mocks base method.
func (m_2 *MockMasterRankingScopeMysqlRepository) Update(ctx context.Context, tx *gorm.DB, m *MasterRankingScope) (*MasterRankingScope, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, tx, m)
	ret0, _ := ret[0].(*MasterRankingScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMasterRankingScopeMysqlRepositoryMockRecorder) Update(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMasterRankingScopeMysqlRepository)(nil).Update), ctx, tx, m)
}
