// プロフィール作成レスポンス

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: profile_create_response.proto

package profile

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserProfile *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3,oneof" json:"user_profile,omitempty"`
}

func (x *ProfileCreateResponse) Reset() {
	*x = ProfileCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_create_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileCreateResponse) ProtoMessage() {}

func (x *ProfileCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_create_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileCreateResponse.ProtoReflect.Descriptor instead.
func (*ProfileCreateResponse) Descriptor() ([]byte, []int) {
	return file_profile_create_response_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileCreateResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

var File_profile_create_response_proto protoreflect.FileDescriptor

var file_profile_create_response_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x61, 0x70,
	0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_profile_create_response_proto_rawDescOnce sync.Once
	file_profile_create_response_proto_rawDescData = file_profile_create_response_proto_rawDesc
)

func file_profile_create_response_proto_rawDescGZIP() []byte {
	file_profile_create_response_proto_rawDescOnce.Do(func() {
		file_profile_create_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_profile_create_response_proto_rawDescData)
	})
	return file_profile_create_response_proto_rawDescData
}

var file_profile_create_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_profile_create_response_proto_goTypes = []interface{}{
	(*ProfileCreateResponse)(nil), // 0: proto.ProfileCreateResponse
	(*UserProfile)(nil),           // 1: proto.UserProfile
}
var file_profile_create_response_proto_depIdxs = []int32{
	1, // 0: proto.ProfileCreateResponse.user_profile:type_name -> proto.UserProfile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_profile_create_response_proto_init() }
func file_profile_create_response_proto_init() {
	if File_profile_create_response_proto != nil {
		return
	}
	file_user_profile_structure_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_profile_create_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_profile_create_response_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profile_create_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_create_response_proto_goTypes,
		DependencyIndexes: file_profile_create_response_proto_depIdxs,
		MessageInfos:      file_profile_create_response_proto_msgTypes,
	}.Build()
	File_profile_create_response_proto = out.File
	file_profile_create_response_proto_rawDesc = nil
	file_profile_create_response_proto_goTypes = nil
	file_profile_create_response_proto_depIdxs = nil
}
