// ルームユーザー立場タイプ

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: room_user_position_type_enum.proto

package room

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomUserPositionType int32

const (
	RoomUserPositionType_Leader  RoomUserPositionType = 0
	RoomUserPositionType_General RoomUserPositionType = 1
)

// Enum value maps for RoomUserPositionType.
var (
	RoomUserPositionType_name = map[int32]string{
		0: "Leader",
		1: "General",
	}
	RoomUserPositionType_value = map[string]int32{
		"Leader":  0,
		"General": 1,
	}
)

func (x RoomUserPositionType) Enum() *RoomUserPositionType {
	p := new(RoomUserPositionType)
	*p = x
	return p
}

func (x RoomUserPositionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomUserPositionType) Descriptor() protoreflect.EnumDescriptor {
	return file_room_user_position_type_enum_proto_enumTypes[0].Descriptor()
}

func (RoomUserPositionType) Type() protoreflect.EnumType {
	return &file_room_user_position_type_enum_proto_enumTypes[0]
}

func (x RoomUserPositionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomUserPositionType.Descriptor instead.
func (RoomUserPositionType) EnumDescriptor() ([]byte, []int) {
	return file_room_user_position_type_enum_proto_rawDescGZIP(), []int{0}
}

var File_room_user_position_type_enum_proto protoreflect.FileDescriptor

var file_room_user_position_type_enum_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x2f, 0x0a, 0x14, 0x52,
	0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x10, 0x01, 0x42, 0x23, 0x5a, 0x21,
	0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x6f,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_user_position_type_enum_proto_rawDescOnce sync.Once
	file_room_user_position_type_enum_proto_rawDescData = file_room_user_position_type_enum_proto_rawDesc
)

func file_room_user_position_type_enum_proto_rawDescGZIP() []byte {
	file_room_user_position_type_enum_proto_rawDescOnce.Do(func() {
		file_room_user_position_type_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_user_position_type_enum_proto_rawDescData)
	})
	return file_room_user_position_type_enum_proto_rawDescData
}

var file_room_user_position_type_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_user_position_type_enum_proto_goTypes = []interface{}{
	(RoomUserPositionType)(0), // 0: proto.RoomUserPositionType
}
var file_room_user_position_type_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_user_position_type_enum_proto_init() }
func file_room_user_position_type_enum_proto_init() {
	if File_room_user_position_type_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_user_position_type_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_user_position_type_enum_proto_goTypes,
		DependencyIndexes: file_room_user_position_type_enum_proto_depIdxs,
		EnumInfos:         file_room_user_position_type_enum_proto_enumTypes,
	}.Build()
	File_room_user_position_type_enum_proto = out.File
	file_room_user_position_type_enum_proto_rawDesc = nil
	file_room_user_position_type_enum_proto_goTypes = nil
	file_room_user_position_type_enum_proto_depIdxs = nil
}
