name: UserProfile
package: userProfile
comment: "ユーザープロフィール"

structure:
  UserId:
    name: user_id
    type: string
    nullable: false
    number: 1
    comment: "ユーザーID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "ユーザープロフィール名"
  Content:
    name: content
    type: string
    nullable: false
    number: 3
    comment: "コンテンツ"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 4
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 5
    comment: "更新日時"
primary:
  - UserId
unique:
  - UserId
