// Code generated by MockGen. DO NOT EDIT.
// Source: ./master_transaction_repository.go

// Package masterTransaction is a generated GoMock package.
package masterTransaction

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockMasterTransactionRepository is a mock of MasterTransactionRepository interface.
type MockMasterTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMasterTransactionRepositoryMockRecorder
}

// MockMasterTransactionRepositoryMockRecorder is the mock recorder for MockMasterTransactionRepository.
type MockMasterTransactionRepositoryMockRecorder struct {
	mock *MockMasterTransactionRepository
}

// NewMockMasterTransactionRepository creates a new mock instance.
func NewMockMasterTransactionRepository(ctrl *gomock.Controller) *MockMasterTransactionRepository {
	mock := &MockMasterTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockMasterTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterTransactionRepository) EXPECT() *MockMasterTransactionRepositoryMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockMasterTransactionRepository) Begin(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockMasterTransactionRepositoryMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockMasterTransactionRepository)(nil).Begin), ctx)
}

// Commit mocks base method.
func (m *MockMasterTransactionRepository) Commit(ctx context.Context, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockMasterTransactionRepositoryMockRecorder) Commit(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockMasterTransactionRepository)(nil).Commit), ctx, tx)
}

// Rollback mocks base method.
func (m *MockMasterTransactionRepository) Rollback(ctx context.Context, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockMasterTransactionRepositoryMockRecorder) Rollback(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockMasterTransactionRepository)(nil).Rollback), ctx, tx)
}
