// Package api GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/check_account": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "アカウント確認",
                "parameters": [
                    {
                        "description": "アカウント確認",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_game-core_gocrafter_api_presentation_request_account.CheckAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_game-core_gocrafter_api_presentation_response_account.CheckAccount"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/error.Error"
                        }
                    }
                }
            }
        },
        "/account/login_account": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "アカウントログイン",
                "parameters": [
                    {
                        "description": "アカウントログイン",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_game-core_gocrafter_api_presentation_request_account.LoginAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_game-core_gocrafter_api_presentation_response_account.LoginAccount"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/error.Error"
                        }
                    }
                }
            }
        },
        "/account/register_account": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "アカウント登録",
                "parameters": [
                    {
                        "description": "アカウント登録",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_game-core_gocrafter_api_presentation_request_account.RegisterAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_game-core_gocrafter_api_presentation_response_account.RegisterAccount"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/error.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.Account": {
            "pointer": "object",
            "properties": {
                "id": {
                    "pointer": "integer"
                },
                "name": {
                    "pointer": "string"
                },
                "password": {
                    "pointer": "string"
                },
                "token": {
                    "pointer": "string"
                },
                "uuid": {
                    "pointer": "string"
                }
            }
        },
        "error.Error": {
            "pointer": "object",
            "properties": {
                "error_message": {
                    "pointer": "string"
                },
                "status": {
                    "pointer": "integer"
                }
            }
        },
        "github.com_game-core_gocrafter_api_presentation_request_account.CheckAccount": {
            "pointer": "object",
            "properties": {
                "uuid": {
                    "pointer": "string"
                }
            }
        },
        "github.com_game-core_gocrafter_api_presentation_request_account.LoginAccount": {
            "pointer": "object",
            "properties": {
                "password": {
                    "pointer": "string"
                },
                "uuid": {
                    "pointer": "string"
                }
            }
        },
        "github.com_game-core_gocrafter_api_presentation_request_account.RegisterAccount": {
            "pointer": "object",
            "properties": {
                "name": {
                    "pointer": "string"
                }
            }
        },
        "github.com_game-core_gocrafter_api_presentation_response_account.CheckAccount": {
            "pointer": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/account.Account"
                },
                "status": {
                    "pointer": "integer"
                }
            }
        },
        "github.com_game-core_gocrafter_api_presentation_response_account.LoginAccount": {
            "pointer": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/account.Account"
                },
                "status": {
                    "pointer": "integer"
                }
            }
        },
        "github.com_game-core_gocrafter_api_presentation_response_account.RegisterAccount": {
            "pointer": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/account.Account"
                },
                "status": {
                    "pointer": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Chat Connect",
	Description:      "This is a sample swagger server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
