name: UserFriend
package: userFriend
comment: "ユーザーフレンド"

structure:
  UserId:
    name: user_id
    type: string
    nullable: false
    number: 1
    comment: "ユーザーID"
  FriendUserId:
    name: friend_user_id
    type: string
    nullable: false
    number: 2
    comment: "フレンドユーザーID"
  FriendType:
    name: friend_type
    type: enum
    nullable: false
    number: 3
    comment: "フレンドタイプ"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 4
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 5
    comment: "更新日時"
primary:
  - UserId,FriendUserId
unique:
  - UserId,FriendUserId
