// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/game-core/gocrafter/batch/command/example"
	"github.com/game-core/gocrafter/config/database"
	example3 "github.com/game-core/gocrafter/domain/service/api/example"
	example2 "github.com/game-core/gocrafter/infra/dao/master/example"
)

// Injectors from wire.go:

func InitializeExampleCommand() example.ExampleCommand {
	sqlHandler := database.NewDB()
	exampleRepository := example2.NewExampleDao(sqlHandler)
	exampleService := example3.NewExampleService(exampleRepository)
	exampleCommand := example.NewExampleCommand(exampleService)
	return exampleCommand
}
