// ランキング範囲タイプ

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v4.24.4
// source: ranking_scope_type_enum.proto

package ranking

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankingScopeType int32

const (
	RankingScopeType_Room  RankingScopeType = 0
	RankingScopeType_World RankingScopeType = 1
)

// Enum value maps for RankingScopeType.
var (
	RankingScopeType_name = map[int32]string{
		0: "Room",
		1: "World",
	}
	RankingScopeType_value = map[string]int32{
		"Room":  0,
		"World": 1,
	}
)

func (x RankingScopeType) Enum() *RankingScopeType {
	p := new(RankingScopeType)
	*p = x
	return p
}

func (x RankingScopeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankingScopeType) Descriptor() protoreflect.EnumDescriptor {
	return file_ranking_scope_type_enum_proto_enumTypes[0].Descriptor()
}

func (RankingScopeType) Type() protoreflect.EnumType {
	return &file_ranking_scope_type_enum_proto_enumTypes[0]
}

func (x RankingScopeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankingScopeType.Descriptor instead.
func (RankingScopeType) EnumDescriptor() ([]byte, []int) {
	return file_ranking_scope_type_enum_proto_rawDescGZIP(), []int{0}
}

var File_ranking_scope_type_enum_proto protoreflect.FileDescriptor

var file_ranking_scope_type_enum_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x27, 0x0a, 0x10, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x6f,
	0x6f, 0x6d, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x10, 0x01, 0x42,
	0x26, 0x5a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ranking_scope_type_enum_proto_rawDescOnce sync.Once
	file_ranking_scope_type_enum_proto_rawDescData = file_ranking_scope_type_enum_proto_rawDesc
)

func file_ranking_scope_type_enum_proto_rawDescGZIP() []byte {
	file_ranking_scope_type_enum_proto_rawDescOnce.Do(func() {
		file_ranking_scope_type_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_ranking_scope_type_enum_proto_rawDescData)
	})
	return file_ranking_scope_type_enum_proto_rawDescData
}

var file_ranking_scope_type_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ranking_scope_type_enum_proto_goTypes = []interface{}{
	(RankingScopeType)(0), // 0: proto.RankingScopeType
}
var file_ranking_scope_type_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ranking_scope_type_enum_proto_init() }
func file_ranking_scope_type_enum_proto_init() {
	if File_ranking_scope_type_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ranking_scope_type_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ranking_scope_type_enum_proto_goTypes,
		DependencyIndexes: file_ranking_scope_type_enum_proto_depIdxs,
		EnumInfos:         file_ranking_scope_type_enum_proto_enumTypes,
	}.Build()
	File_ranking_scope_type_enum_proto = out.File
	file_ranking_scope_type_enum_proto_rawDesc = nil
	file_ranking_scope_type_enum_proto_goTypes = nil
	file_ranking_scope_type_enum_proto_depIdxs = nil
}
