name: ConfigType
package: enum
comment: "設定タイプ"

structure:
  MaxRoomNumber:
    name: MaxRoomNumber
    number: 0
    comment: "最大ルーム番号"
  MaxRoomUser:
    name: MaxRoomUser
    number: 1
    comment: "最大ルームユーザー数"
