name: MasterActionRun
package: masterActionRun
comment: "実行されるアクション"

structure:
  Id:
    name: id
    type: int64
    nullable: false
    number: 1
    comment: "ID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "実行されるアクション名"
  ActionId:
    name: action_id
    type: int64
    nullable: false
    number: 3
    comment: "アクションID"
primary:
  - Id
unique:
  - Id
index:
  - Name
  - ActionId
