// Code generated by MockGen. DO NOT EDIT.
// Source: ./ranking_service.go

// Package ranking is a generated GoMock package.
package ranking

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRankingService is a mock of RankingService interface.
type MockRankingService struct {
	ctrl     *gomock.Controller
	recorder *MockRankingServiceMockRecorder
}

// MockRankingServiceMockRecorder is the mock recorder for MockRankingService.
type MockRankingServiceMockRecorder struct {
	mock *MockRankingService
}

// NewMockRankingService creates a new mock instance.
func NewMockRankingService(ctrl *gomock.Controller) *MockRankingService {
	mock := &MockRankingService{ctrl: ctrl}
	mock.recorder = &MockRankingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingService) EXPECT() *MockRankingServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRankingService) Get(ctx context.Context, req *RankingGetRequest) (*RankingGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(*RankingGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRankingServiceMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRankingService)(nil).Get), ctx, req)
}
