name: UserAction
package: userAction
comment: "ユーザーアクション"

structure:
  UserId:
    name: user_id
    type: string
    nullable: false
    number: 1
    comment: "ユーザーID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "ユーザー名"
  MasterActionId:
    name: master_action_id
    type: int64
    nullable: false
    number: 3
    comment: "マスターアクションID"
  StartedAt:
    name: started_at
    type: time
    nullable: false
    number: 4
    comment: "開始日時"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 5
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 6
    comment: "更新日時"
primary:
  - UserId,MasterActionId
unique:
  - UserId,MasterActionId
