// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/game-core/gocrafter/auth/presentation/controller/account"
	"github.com/game-core/gocrafter/config/database"
	account2 "github.com/game-core/gocrafter/domain/service/auth/account"
	"github.com/game-core/gocrafter/infra/dao/auth"
	account3 "github.com/game-core/gocrafter/infra/dao/auth/account"
)

// Injectors from wire.go:

func InitializeAccountController() account.AccountController {
	accountService := InitializeAccountService()
	accountController := account.NewAccountController(accountService)
	return accountController
}

func InitializeAccountService() account2.AccountService {
	sqlHandler := database.NewDB()
	transactionRepository := config.NewTransactionDao(sqlHandler)
	accountRepository := account3.NewAccountDao(sqlHandler)
	accountService := account2.NewAccountService(transactionRepository, accountRepository)
	return accountService
}
