name: UserItemBox
package: userItemBox
comment: "ユーザーアイテムボックス"

structure:
  UserId:
    name: user_id
    type: string
    nullable: false
    number: 1
    comment: "ユーザーID"
  MasterItemId:
    name: master_item_id
    type: int64
    nullable: false
    number: 2
    comment: "アイテムID"
  Count:
    name: count
    type: int32
    nullable: false
    number: 3
    comment: "個数"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 4
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 5
    comment: "更新日時"
primary:
  - UserId,MasterItemId
unique:
  - UserId,MasterItemId
index:
