// Code generated by MockGen. DO NOT EDIT.
// Source: ./login_bonus_service.go

// Package loginBonus is a generated GoMock package.
package loginBonus

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockLoginBonusService is a mock of LoginBonusService interface.
type MockLoginBonusService struct {
	ctrl     *gomock.Controller
	recorder *MockLoginBonusServiceMockRecorder
}

// MockLoginBonusServiceMockRecorder is the mock recorder for MockLoginBonusService.
type MockLoginBonusServiceMockRecorder struct {
	mock *MockLoginBonusService
}

// NewMockLoginBonusService creates a new mock instance.
func NewMockLoginBonusService(ctrl *gomock.Controller) *MockLoginBonusService {
	mock := &MockLoginBonusService{ctrl: ctrl}
	mock.recorder = &MockLoginBonusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginBonusService) EXPECT() *MockLoginBonusServiceMockRecorder {
	return m.recorder
}

// Receive mocks base method.
func (m *MockLoginBonusService) Receive(ctx context.Context, tx *gorm.DB, now time.Time, req *LoginBonusReceiveRequest) (*LoginBonusReceiveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", ctx, tx, now, req)
	ret0, _ := ret[0].(*LoginBonusReceiveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockLoginBonusServiceMockRecorder) Receive(ctx, tx, now, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockLoginBonusService)(nil).Receive), ctx, tx, now, req)
}
