apiVersion: v1
kind: Service
metadata:
  name: gocrafter-api-game-service
  namespace: gocrafter-api-game
spec:
  type: NodePort
  selector:
    app: gocrafter-api-game
  ports:
    - protocol:  TCP
      port: 50051
      nodePort: 30001
