basePath: /
definitions:
  account.Account:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      token:
        type: string
    type: object
  error.Error:
    properties:
      error_message:
        type: string
      status:
        type: integer
    type: object
  github.com_game-core_gocrafter_auth_presentation_request_account.CheckAccount:
    properties:
      email:
        type: string
    type: object
  github.com_game-core_gocrafter_auth_presentation_request_account.LoginAccount:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  github.com_game-core_gocrafter_auth_presentation_request_account.RegisterAccount:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  github.com_game-core_gocrafter_auth_presentation_response_account.CheckAccount:
    properties:
      account:
        $ref: '#/definitions/account.Account'
      status:
        type: integer
    type: object
  github.com_game-core_gocrafter_auth_presentation_response_account.LoginAccount:
    properties:
      account:
        $ref: '#/definitions/account.Account'
      status:
        type: integer
    type: object
  github.com_game-core_gocrafter_auth_presentation_response_account.RegisterAccount:
    properties:
      account:
        $ref: '#/definitions/account.Account'
      status:
        type: integer
    type: object
host: localhost:8002
info:
  contact: {}
  description: This is a sample swagger server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: github.com/game-core/gocrafter
  version: "1.0"
paths:
  /account/check_account:
    post:
      consumes:
      - application/json
      parameters:
      - description: アカウント確認
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_game-core_gocrafter_auth_presentation_request_account.CheckAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_game-core_gocrafter_auth_presentation_response_account.CheckAccount'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: アカウント確認
      tags:
      - Account
  /account/login_account:
    post:
      consumes:
      - application/json
      parameters:
      - description: アカウントログイン
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_game-core_gocrafter_auth_presentation_request_account.LoginAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_game-core_gocrafter_auth_presentation_response_account.LoginAccount'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: アカウントログイン
      tags:
      - Account
  /account/register_account:
    post:
      consumes:
      - application/json
      parameters:
      - description: アカウント登録
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_game-core_gocrafter_auth_presentation_request_account.RegisterAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_game-core_gocrafter_auth_presentation_response_account.RegisterAccount'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: アカウント登録
      tags:
      - Account
swagger: "2.0"
