name: CommonShard
package: commonShard
comment: "シャード管理"

structure:
  Id:
    name: id
    type: int64
    nullable: false
    number: 1
    comment: "ID"
  ShardKey:
    name: shard_key
    type: string
    nullable: false
    number: 2
    comment: "シャードキー"
  Name:
    name: name
    type: string
    nullable: false
    number: 3
    comment: "シャード名"
  Count:
    name: count
    type: int32
    nullable: false
    number: 4
    comment: "シャードされたユーザー数"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 5
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 6
    comment: "更新日時"
