name: Config
package: example
structure:
  GetConfig:
    name: get_config
    type: int64
    nullable: false
    number: 1
  SetConfig:
    name: set_config
    type: int64
    nullable: false
    number: 2
