// Code generated by MockGen. DO NOT EDIT.
// Source: ./master_idle_bonus_event_repository.gen.go

// Package masterIdleBonusEvent is a generated GoMock package.
package masterIdleBonusEvent

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockMasterIdleBonusEventRepository is a mock of MasterIdleBonusEventRepository interface.
type MockMasterIdleBonusEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMasterIdleBonusEventRepositoryMockRecorder
}

// MockMasterIdleBonusEventRepositoryMockRecorder is the mock recorder for MockMasterIdleBonusEventRepository.
type MockMasterIdleBonusEventRepositoryMockRecorder struct {
	mock *MockMasterIdleBonusEventRepository
}

// NewMockMasterIdleBonusEventRepository creates a new mock instance.
func NewMockMasterIdleBonusEventRepository(ctrl *gomock.Controller) *MockMasterIdleBonusEventRepository {
	mock := &MockMasterIdleBonusEventRepository{ctrl: ctrl}
	mock.recorder = &MockMasterIdleBonusEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterIdleBonusEventRepository) EXPECT() *MockMasterIdleBonusEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockMasterIdleBonusEventRepository) Create(ctx context.Context, tx *gorm.DB, m *MasterIdleBonusEvent) (*MasterIdleBonusEvent, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, tx, m)
	ret0, _ := ret[0].(*MasterIdleBonusEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMasterIdleBonusEventRepositoryMockRecorder) Create(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMasterIdleBonusEventRepository)(nil).Create), ctx, tx, m)
}

// CreateList mocks base method.
func (m *MockMasterIdleBonusEventRepository) CreateList(ctx context.Context, tx *gorm.DB, ms MasterIdleBonusEvents) (MasterIdleBonusEvents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateList", ctx, tx, ms)
	ret0, _ := ret[0].(MasterIdleBonusEvents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateList indicates an expected call of CreateList.
func (mr *MockMasterIdleBonusEventRepositoryMockRecorder) CreateList(ctx, tx, ms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateList", reflect.TypeOf((*MockMasterIdleBonusEventRepository)(nil).CreateList), ctx, tx, ms)
}

// Delete mocks base method.
func (m_2 *MockMasterIdleBonusEventRepository) Delete(ctx context.Context, tx *gorm.DB, m *MasterIdleBonusEvent) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Delete", ctx, tx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMasterIdleBonusEventRepositoryMockRecorder) Delete(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMasterIdleBonusEventRepository)(nil).Delete), ctx, tx, m)
}

// Find mocks base method.
func (m *MockMasterIdleBonusEventRepository) Find(ctx context.Context, id int64) (*MasterIdleBonusEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*MasterIdleBonusEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMasterIdleBonusEventRepositoryMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMasterIdleBonusEventRepository)(nil).Find), ctx, id)
}

// FindList mocks base method.
func (m *MockMasterIdleBonusEventRepository) FindList(ctx context.Context) (MasterIdleBonusEvents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx)
	ret0, _ := ret[0].(MasterIdleBonusEvents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockMasterIdleBonusEventRepositoryMockRecorder) FindList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockMasterIdleBonusEventRepository)(nil).FindList), ctx)
}

// FindOrNil mocks base method.
func (m *MockMasterIdleBonusEventRepository) FindOrNil(ctx context.Context, id int64) (*MasterIdleBonusEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNil", ctx, id)
	ret0, _ := ret[0].(*MasterIdleBonusEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNil indicates an expected call of FindOrNil.
func (mr *MockMasterIdleBonusEventRepositoryMockRecorder) FindOrNil(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNil", reflect.TypeOf((*MockMasterIdleBonusEventRepository)(nil).FindOrNil), ctx, id)
}

// Update mocks base method.
func (m_2 *MockMasterIdleBonusEventRepository) Update(ctx context.Context, tx *gorm.DB, m *MasterIdleBonusEvent) (*MasterIdleBonusEvent, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, tx, m)
	ret0, _ := ret[0].(*MasterIdleBonusEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMasterIdleBonusEventRepositoryMockRecorder) Update(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMasterIdleBonusEventRepository)(nil).Update), ctx, tx, m)
}
