name: test

on:
  pull_request:
    branches:
      - main

jobs:
  usecase_test:
    name: Run Usecase Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker compose -f docker-compose.test.yaml up -d --build

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Usecase Test
        run: docker compose -f docker-compose.test.yaml exec api-game-test go test -v ./api/game/usecase/...

  domain_test:
    name: Run Domain Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker compose -f docker-compose.test.yaml up -d --build

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Domain Test
        run: docker compose -f docker-compose.test.yaml exec api-game-test go test -v ./pkg/domain/...
