name: test

on:
  pull_request:
    branches:
      - main

jobs:
  domain_test:
    name: Run Domain Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker compose -f docker-compose.test.yaml up -d --build --init

      - name: usecase Test
        run: docker compose -f docker-compose.test.yaml exec api-game-test go test -v ./api/game/usecase/...

      - name: Domain Test
        run: docker compose -f docker-compose.test.yaml exec api-game-test go test -v ./pkg/domain/...
