name: test

on:
  pull_request:
    branches:
      - main

jobs:
  domain_test:
    name: Run Domain Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        run: docker compose -f docker-compose.test.yaml up -d --build

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Usecase Test
        run: go test -v ./api/game/usecase/...

      - name: Domain Test
        run: go test -v ./pkg/domain/...
