name: test

on:
  pull_request:
    branches:
      - main

jobs:
  domain_test:
    name: Run Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker compose -f docker-compose.test.yaml up -d --build

      - name: Sleep for 20 seconds
        run: sleep 20

      - name: Test
        run: make docker_test_run
