// Code generated by MockGen. DO NOT EDIT.
// Source: ./master_rarity_repository.gen.go

// Package masterRarity is a generated GoMock package.
package masterRarity

import (
	context "context"
	reflect "reflect"

	enum "github.com/game-core/gocrafter/pkg/domain/enum"
	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockMasterRarityRepository is a mock of MasterRarityRepository interface.
type MockMasterRarityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMasterRarityRepositoryMockRecorder
}

// MockMasterRarityRepositoryMockRecorder is the mock recorder for MockMasterRarityRepository.
type MockMasterRarityRepositoryMockRecorder struct {
	mock *MockMasterRarityRepository
}

// NewMockMasterRarityRepository creates a new mock instance.
func NewMockMasterRarityRepository(ctrl *gomock.Controller) *MockMasterRarityRepository {
	mock := &MockMasterRarityRepository{ctrl: ctrl}
	mock.recorder = &MockMasterRarityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterRarityRepository) EXPECT() *MockMasterRarityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockMasterRarityRepository) Create(ctx context.Context, tx *gorm.DB, m *MasterRarity) (*MasterRarity, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, tx, m)
	ret0, _ := ret[0].(*MasterRarity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMasterRarityRepositoryMockRecorder) Create(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMasterRarityRepository)(nil).Create), ctx, tx, m)
}

// CreateList mocks base method.
func (m *MockMasterRarityRepository) CreateList(ctx context.Context, tx *gorm.DB, ms MasterRarities) (MasterRarities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateList", ctx, tx, ms)
	ret0, _ := ret[0].(MasterRarities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateList indicates an expected call of CreateList.
func (mr *MockMasterRarityRepositoryMockRecorder) CreateList(ctx, tx, ms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateList", reflect.TypeOf((*MockMasterRarityRepository)(nil).CreateList), ctx, tx, ms)
}

// Delete mocks base method.
func (m_2 *MockMasterRarityRepository) Delete(ctx context.Context, tx *gorm.DB, m *MasterRarity) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Delete", ctx, tx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMasterRarityRepositoryMockRecorder) Delete(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMasterRarityRepository)(nil).Delete), ctx, tx, m)
}

// FindOrNilByRarityType mocks base method.
func (m *MockMasterRarityRepository) FindOrNilByRarityType(ctx context.Context, rarityType enum.RarityType) (*MasterRarity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNilByRarityType", ctx, rarityType)
	ret0, _ := ret[0].(*MasterRarity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNilByRarityType indicates an expected call of FindOrNilByRarityType.
func (mr *MockMasterRarityRepositoryMockRecorder) FindOrNilByRarityType(ctx, rarityType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNilByRarityType", reflect.TypeOf((*MockMasterRarityRepository)(nil).FindOrNilByRarityType), ctx, rarityType)
}

// Find mocks base method.
func (m *MockMasterRarityRepository) Find(ctx context.Context, id int64) (*MasterRarity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*MasterRarity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMasterRarityRepositoryMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMasterRarityRepository)(nil).Find), ctx, id)
}

// FindByRarityType mocks base method.
func (m *MockMasterRarityRepository) FindByRarityType(ctx context.Context, rarityType enum.RarityType) (*MasterRarity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRarityType", ctx, rarityType)
	ret0, _ := ret[0].(*MasterRarity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRarityType indicates an expected call of FindByRarityType.
func (mr *MockMasterRarityRepositoryMockRecorder) FindByRarityType(ctx, rarityType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRarityType", reflect.TypeOf((*MockMasterRarityRepository)(nil).FindByRarityType), ctx, rarityType)
}

// FindList mocks base method.
func (m *MockMasterRarityRepository) FindList(ctx context.Context) (MasterRarities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx)
	ret0, _ := ret[0].(MasterRarities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockMasterRarityRepositoryMockRecorder) FindList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockMasterRarityRepository)(nil).FindList), ctx)
}

// FindListByRarityType mocks base method.
func (m *MockMasterRarityRepository) FindListByRarityType(ctx context.Context, rarityType enum.RarityType) (MasterRarities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindListByRarityType", ctx, rarityType)
	ret0, _ := ret[0].(MasterRarities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindListByRarityType indicates an expected call of FindListByRarityType.
func (mr *MockMasterRarityRepositoryMockRecorder) FindListByRarityType(ctx, rarityType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindListByRarityType", reflect.TypeOf((*MockMasterRarityRepository)(nil).FindListByRarityType), ctx, rarityType)
}

// FindOrNil mocks base method.
func (m *MockMasterRarityRepository) FindOrNil(ctx context.Context, id int64) (*MasterRarity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrNil", ctx, id)
	ret0, _ := ret[0].(*MasterRarity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrNil indicates an expected call of FindOrNil.
func (mr *MockMasterRarityRepositoryMockRecorder) FindOrNil(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrNil", reflect.TypeOf((*MockMasterRarityRepository)(nil).FindOrNil), ctx, id)
}

// Update mocks base method.
func (m_2 *MockMasterRarityRepository) Update(ctx context.Context, tx *gorm.DB, m *MasterRarity) (*MasterRarity, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, tx, m)
	ret0, _ := ret[0].(*MasterRarity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMasterRarityRepositoryMockRecorder) Update(ctx, tx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMasterRarityRepository)(nil).Update), ctx, tx, m)
}
