// Code generated by MockGen. DO NOT EDIT.
// Source: ./config_service.go

// Package config is a generated GoMock package.
package config

import (
	context "context"
	reflect "reflect"

	enum "github.com/game-core/gocrafter/pkg/domain/enum"
	masterConfig "github.com/game-core/gocrafter/pkg/domain/model/config/masterConfig"
	gomock "github.com/golang/mock/gomock"
)

// MockConfigService is a mock of ConfigService interface.
type MockConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceMockRecorder
}

// MockConfigServiceMockRecorder is the mock recorder for MockConfigService.
type MockConfigServiceMockRecorder struct {
	mock *MockConfigService
}

// NewMockConfigService creates a new mock instance.
func NewMockConfigService(ctrl *gomock.Controller) *MockConfigService {
	mock := &MockConfigService{ctrl: ctrl}
	mock.recorder = &MockConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigService) EXPECT() *MockConfigServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigService) Get(cxt context.Context, configType enum.ConfigType) (*masterConfig.MasterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", cxt, configType)
	ret0, _ := ret[0].(*masterConfig.MasterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigServiceMockRecorder) Get(cxt, configType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigService)(nil).Get), cxt, configType)
}

// GetAll mocks base method.
func (m *MockConfigService) GetAll(cxt context.Context) (masterConfig.MasterConfigs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", cxt)
	ret0, _ := ret[0].(masterConfig.MasterConfigs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockConfigServiceMockRecorder) GetAll(cxt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockConfigService)(nil).GetAll), cxt)
}

// GetInt32 mocks base method.
func (m *MockConfigService) GetInt32(cxt context.Context, configType enum.ConfigType) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt32", cxt, configType)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInt32 indicates an expected call of GetInt32.
func (mr *MockConfigServiceMockRecorder) GetInt32(cxt, configType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt32", reflect.TypeOf((*MockConfigService)(nil).GetInt32), cxt, configType)
}
